services:
  index-tts-server:
    image: index-tts-image:0.1
    hostname: index-tts-server
    container_name: index-tts-server
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 192.168.3.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - AIGC_UID=${AIGC_UID:-1001}
      - AIGC_GID=${AIGC_GID:-1001}
      - TZ=Asia/Shanghai
    volumes:
      - /home/aigc/work/models/aivoice_models/indextts_models/IndexTTS-2:/app/index-tts/checkpoints
      - /home/aigc/work/models/aivoice_models/indextts_models/w2v-bert-2.0:/app/index-tts/models/w2v-bert-2.0
      - /home/aigc/work/models/aivoice_models/indextts_models/MaskGCT:/app/index-tts/models/MaskGCT
      - /home/aigc/work/models/aivoice_models/indextts_models/campplus:/app/index-tts/models/campplus
      - /home/aigc/work/models/aivoice_models/indextts_models/bigvgan_v2_22khz_80band_256x:/app/index-tts/models/bigvgan_v2_22khz_80band_256x
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #tty: true
